{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/authentication\/oauthprovidererror\/errordescription-6lavv"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/errorDescription-6lavv","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.errorDescription"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"errorDescription","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:14Authentication18OAuthProviderErrorO16errorDescriptionSSSgvp","modules":[{"name":"Authentication"}]},"hierarchy":{"paths":[["doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication","doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError"]]},"references":{"doc://com.ibm.iOS-SDK/documentation/Authentication/OAuthProviderError":{"role":"symbol","title":"OAuthProviderError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuthProviderError"}],"abstract":[{"type":"text","text":"A type that indicates when OAuth operartion encounters an error."}],"identifier":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OAuthProviderError"}],"url":"\/documentation\/authentication\/oauthprovidererror"},"doc://com.ibm.iOS-SDK/documentation/Authentication":{"role":"collection","title":"Authentication","abstract":[],"identifier":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication","kind":"symbol","type":"topic","url":"\/documentation\/authentication"},"doc://com.ibm.iOS-SDK/documentation/Authentication/OAuthProviderError/errorDescription-6lavv":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/errorDescription-6lavv","kind":"symbol","type":"topic","url":"\/documentation\/authentication\/oauthprovidererror\/errordescription-6lavv"}}}