{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError"]]},"identifier":{"url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/errorDescription","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"LocalizedError.errorDescription","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/authentication\/oauthprovidererror\/errordescription"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"title":"errorDescription","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","externalID":"s:14Authentication18OAuthProviderErrorO16errorDescriptionSSSgvp","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"Authentication"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/errorDescription":{"url":"\/documentation\/authentication\/oauthprovidererror\/errordescription","type":"topic","abstract":[],"title":"errorDescription","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/errorDescription","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError":{"abstract":[{"type":"text","text":"A type that indicates when OAuth operartion encounters an error."}],"kind":"symbol","url":"\/documentation\/authentication\/oauthprovidererror","title":"OAuthProviderError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"OAuthProviderError","kind":"identifier"}],"navigatorTitle":[{"text":"OAuthProviderError","kind":"identifier"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError","type":"topic","role":"symbol"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication":{"abstract":[],"title":"Authentication","url":"\/documentation\/authentication","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication","role":"collection","kind":"symbol","type":"topic"}}}