{"identifier":{"url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Core\/URLSessionError\/transportFailed(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Core","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Core\/URLSessionError"]]},"abstract":[{"type":"text","text":"An error occured establishing the networking connection."}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/core\/urlsessionerror\/transportfailed(_:)"]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"transportFailed","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","title":"URLSessionError.transportFailed(_:)","roleHeading":"Case","modules":[{"name":"Core"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transportFailed"},{"kind":"text","text":"("},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"externalID":"s:4Core15URLSessionErrorO15transportFailedyACs0C0_pcACmF"},"references":{"doc://com.ibm.verify.ios.sdk/documentation/Core/URLSessionError/transportFailed(_:)":{"kind":"symbol","abstract":[{"text":"An error occured establishing the networking connection.","type":"text"}],"role":"symbol","title":"URLSessionError.transportFailed(_:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"transportFailed"},{"text":"(","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Core\/URLSessionError\/transportFailed(_:)","url":"\/documentation\/core\/urlsessionerror\/transportfailed(_:)","type":"topic"},"doc://com.ibm.verify.ios.sdk/documentation/Core":{"abstract":[],"role":"collection","type":"topic","title":"Core","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Core","url":"\/documentation\/core","kind":"symbol"},"doc://com.ibm.verify.ios.sdk/documentation/Core/URLSessionError":{"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Core\/URLSessionError","role":"symbol","url":"\/documentation\/core\/urlsessionerror","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"URLSessionError","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"URLSessionError"}],"abstract":[{"text":"An error that occurs during URLSession operations.","type":"text"}],"title":"URLSessionError"}}}