{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PublicKeyCredentialError","kind":"identifier"}],"platforms":["iOS"]}]}],"abstract":[{"text":"A type that indicates when Fido2ApiClient encounters an error.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fido2\/publickeycredentialerror"]}],"kind":"symbol","sections":[],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/10Foundation14LocalizedErrorP","doc:\/\/com.ibm.verify.ios.sdk\/SQ","doc:\/\/com.ibm.verify.ios.sdk\/s5ErrorP","doc:\/\/com.ibm.verify.ios.sdk\/s8SendableP"],"kind":"relationships"}],"metadata":{"title":"PublicKeyCredentialError","symbolKind":"enum","role":"symbol","externalID":"s:5FIDO224PublicKeyCredentialErrorO","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PublicKeyCredentialError","kind":"identifier"}],"modules":[{"name":"FIDO2"}],"navigatorTitle":[{"kind":"identifier","text":"PublicKeyCredentialError"}],"roleHeading":"Enumeration"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError"},"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2"]]},"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/general(message:)","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidAttestationData","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidCertificate","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidPrivateKeyData","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/timeout","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateKey","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateSignature"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/errorDescription"]},{"identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/Equatable-Implementations","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/Error-Implementations","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/LocalizedError-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError":{"navigatorTitle":[{"text":"PublicKeyCredentialError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError","title":"PublicKeyCredentialError","abstract":[{"type":"text","text":"A type that indicates when Fido2ApiClient encounters an error."}],"url":"\/documentation\/fido2\/publickeycredentialerror","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PublicKeyCredentialError"}],"kind":"symbol"},"doc://com.ibm.verify.ios.sdk/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/s8SendableP"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/Equatable-Implementations":{"url":"\/documentation\/fido2\/publickeycredentialerror\/equatable-implementations","kind":"article","type":"topic","title":"Equatable Implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/Equatable-Implementations"},"doc://com.ibm.verify.ios.sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/SQ"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/unableToCreateSignature":{"kind":"symbol","url":"\/documentation\/fido2\/publickeycredentialerror\/unabletocreatesignature","title":"PublicKeyCredentialError.unableToCreateSignature","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateSignature","role":"symbol","abstract":[{"type":"text","text":"Unable to create a signature based on the private key and attestation data."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unableToCreateSignature"}],"type":"topic"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2":{"type":"topic","role":"collection","kind":"symbol","title":"FIDO2","url":"\/documentation\/fido2","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2","abstract":[]},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/LocalizedError-Implementations":{"url":"\/documentation\/fido2\/publickeycredentialerror\/localizederror-implementations","kind":"article","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/LocalizedError-Implementations","type":"topic","role":"collectionGroup"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/timeout":{"abstract":[{"type":"text","text":"The time allocated to complete the operation has expired."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"timeout","kind":"identifier"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/timeout","url":"\/documentation\/fido2\/publickeycredentialerror\/timeout","kind":"symbol","type":"topic","role":"symbol","title":"PublicKeyCredentialError.timeout"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/general(message:)":{"title":"PublicKeyCredentialError.general(message:)","abstract":[{"type":"text","text":"General error with custom message."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"general","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fido2\/publickeycredentialerror\/general(message:)","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/general(message:)","type":"topic"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/invalidCertificate":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidCertificate","kind":"identifier"}],"title":"PublicKeyCredentialError.invalidCertificate","type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidCertificate","url":"\/documentation\/fido2\/publickeycredentialerror\/invalidcertificate","abstract":[{"text":"The certifcate could not be parsed.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/errorDescription":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/errorDescription","type":"topic","title":"errorDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/fido2\/publickeycredentialerror\/errordescription"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/Error-Implementations":{"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/Error-Implementations","role":"collectionGroup","type":"topic","abstract":[],"title":"Error Implementations","url":"\/documentation\/fido2\/publickeycredentialerror\/error-implementations","kind":"article"},"doc://com.ibm.verify.ios.sdk/10Foundation14LocalizedErrorP":{"type":"unresolvable","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/invalidAttestationData":{"kind":"symbol","abstract":[{"type":"text","text":"Authentication data or client data hash is invalid."}],"title":"PublicKeyCredentialError.invalidAttestationData","role":"symbol","type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidAttestationData","url":"\/documentation\/fido2\/publickeycredentialerror\/invalidattestationdata","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidAttestationData"}]},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/invalidPrivateKeyData":{"url":"\/documentation\/fido2\/publickeycredentialerror\/invalidprivatekeydata","title":"PublicKeyCredentialError.invalidPrivateKeyData","role":"symbol","abstract":[{"type":"text","text":"The private key data provided was invalid."}],"type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidPrivateKeyData","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidPrivateKeyData","kind":"identifier"}],"kind":"symbol"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/unableToCreateKey":{"abstract":[{"text":"A private key could not be created from the the private key data.","type":"text"}],"title":"PublicKeyCredentialError.unableToCreateKey","url":"\/documentation\/fido2\/publickeycredentialerror\/unabletocreatekey","type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateKey","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unableToCreateKey","kind":"identifier"}]},"doc://com.ibm.verify.ios.sdk/s5ErrorP":{"type":"unresolvable","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/s5ErrorP","title":"Swift.Error"}}}