{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/fido2\/publickeycredentialerror"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError"},"relationshipsSections":[{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/10Foundation14LocalizedErrorP","doc:\/\/com.ibm.verify.ios.sdk\/SQ","doc:\/\/com.ibm.verify.ios.sdk\/s5ErrorP","doc:\/\/com.ibm.verify.ios.sdk\/s8SendableP"]}],"metadata":{"role":"symbol","symbolKind":"enum","modules":[{"name":"FIDO2"}],"roleHeading":"Enumeration","navigatorTitle":[{"text":"PublicKeyCredentialError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PublicKeyCredentialError","kind":"identifier"}],"title":"PublicKeyCredentialError","externalID":"s:5FIDO224PublicKeyCredentialErrorO"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"A type that indicates when Fido2ApiClient encounters an error."}],"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/general(message:)","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidAttestationData","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidCertificate","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidPrivateKeyData","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/timeout","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateKey","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateSignature"],"generated":true},{"identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/errorDescription"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/Equatable-Implementations","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/Error-Implementations","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/LocalizedError-Implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PublicKeyCredentialError"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/general(message:)":{"abstract":[{"type":"text","text":"General error with custom message."}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/general(message:)","url":"\/documentation\/fido2\/publickeycredentialerror\/general(message:)","title":"PublicKeyCredentialError.general(message:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"general","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/timeout":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/timeout","role":"symbol","title":"PublicKeyCredentialError.timeout","abstract":[{"type":"text","text":"The time allocated to complete the operation has expired."}],"url":"\/documentation\/fido2\/publickeycredentialerror\/timeout","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeout","kind":"identifier"}]},"doc://com.ibm.verify.ios.sdk/10Foundation14LocalizedErrorP":{"type":"unresolvable","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError"},"doc://com.ibm.verify.ios.sdk/s5ErrorP":{"type":"unresolvable","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/s5ErrorP","title":"Swift.Error"},"doc://com.ibm.verify.ios.sdk/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/s8SendableP","title":"Swift.Sendable"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError":{"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError","title":"PublicKeyCredentialError","type":"topic","url":"\/documentation\/fido2\/publickeycredentialerror","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PublicKeyCredentialError"}],"role":"symbol","navigatorTitle":[{"text":"PublicKeyCredentialError","kind":"identifier"}],"abstract":[{"text":"A type that indicates when Fido2ApiClient encounters an error.","type":"text"}],"kind":"symbol"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/unableToCreateKey":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateKey","role":"symbol","title":"PublicKeyCredentialError.unableToCreateKey","abstract":[{"type":"text","text":"A private key could not be created from the the private key data."}],"url":"\/documentation\/fido2\/publickeycredentialerror\/unabletocreatekey","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unableToCreateKey","kind":"identifier"}]},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/Error-Implementations":{"abstract":[],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/Error-Implementations","url":"\/documentation\/fido2\/publickeycredentialerror\/error-implementations","title":"Error Implementations","role":"collectionGroup","kind":"article","type":"topic"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/errorDescription":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/errorDescription","role":"symbol","title":"errorDescription","abstract":[],"url":"\/documentation\/fido2\/publickeycredentialerror\/errordescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/invalidCertificate":{"abstract":[{"text":"The certifcate could not be parsed.","type":"text"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidCertificate","url":"\/documentation\/fido2\/publickeycredentialerror\/invalidcertificate","title":"PublicKeyCredentialError.invalidCertificate","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCertificate","kind":"identifier"}],"type":"topic"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/Equatable-Implementations":{"kind":"article","type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/fido2\/publickeycredentialerror\/equatable-implementations"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/invalidPrivateKeyData":{"abstract":[{"type":"text","text":"The private key data provided was invalid."}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidPrivateKeyData","url":"\/documentation\/fido2\/publickeycredentialerror\/invalidprivatekeydata","title":"PublicKeyCredentialError.invalidPrivateKeyData","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidPrivateKeyData","kind":"identifier"}],"type":"topic"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/unableToCreateSignature":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateSignature","role":"symbol","title":"PublicKeyCredentialError.unableToCreateSignature","abstract":[{"text":"Unable to create a signature based on the private key and attestation data.","type":"text"}],"url":"\/documentation\/fido2\/publickeycredentialerror\/unabletocreatesignature","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unableToCreateSignature","kind":"identifier"}]},"doc://com.ibm.verify.ios.sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/SQ"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/LocalizedError-Implementations":{"kind":"article","type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/LocalizedError-Implementations","role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"url":"\/documentation\/fido2\/publickeycredentialerror\/localizederror-implementations"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2":{"role":"collection","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/fido2","title":"FIDO2","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/invalidAttestationData":{"url":"\/documentation\/fido2\/publickeycredentialerror\/invalidattestationdata","abstract":[{"text":"Authentication data or client data hash is invalid.","type":"text"}],"title":"PublicKeyCredentialError.invalidAttestationData","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidAttestationData","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidAttestationData","kind":"identifier"}]}}}