{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuthProviderError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/authentication\/oauthprovidererror"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.ibm.iOS-SDK\/10Foundation14LocalizedErrorP","doc:\/\/com.ibm.iOS-SDK\/SQ","doc:\/\/com.ibm.iOS-SDK\/s5ErrorP","doc:\/\/com.ibm.iOS-SDK\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A type that indicates when OAuth operartion encounters an error."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuthProviderError"}],"title":"OAuthProviderError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"s:14Authentication18OAuthProviderErrorO","modules":[{"name":"Authentication"}],"navigatorTitle":[{"kind":"identifier","text":"OAuthProviderError"}]},"hierarchy":{"paths":[["doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/failed","doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/general(message:)","doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/invalidResponse"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/errorDescription-6lavv"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/Equatable-Implementations","doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/Error-Implementations","doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/LocalizedError-Implementations"],"generated":true}],"references":{"doc://com.ibm.iOS-SDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.ibm.iOS-SDK\/SQ"},"doc://com.ibm.iOS-SDK/documentation/Authentication/OAuthProviderError/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/LocalizedError-Implementations","kind":"article","type":"topic","url":"\/documentation\/authentication\/oauthprovidererror\/localizederror-implementations"},"doc://com.ibm.iOS-SDK/documentation/Authentication/OAuthProviderError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/authentication\/oauthprovidererror\/error-implementations"},"doc://com.ibm.iOS-SDK/documentation/Authentication":{"role":"collection","title":"Authentication","abstract":[],"identifier":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication","kind":"symbol","type":"topic","url":"\/documentation\/authentication"},"doc://com.ibm.iOS-SDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.ibm.iOS-SDK\/s8SendableP"},"doc://com.ibm.iOS-SDK/documentation/Authentication/OAuthProviderError/errorDescription-6lavv":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/errorDescription-6lavv","kind":"symbol","type":"topic","url":"\/documentation\/authentication\/oauthprovidererror\/errordescription-6lavv"},"doc://com.ibm.iOS-SDK/documentation/Authentication/OAuthProviderError/invalidResponse":{"role":"symbol","title":"OAuthProviderError.invalidResponse","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidResponse"}],"abstract":[{"type":"text","text":"The authorization request received an invalid response."}],"identifier":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/invalidResponse","kind":"symbol","type":"topic","url":"\/documentation\/authentication\/oauthprovidererror\/invalidresponse"},"doc://com.ibm.iOS-SDK/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.ibm.iOS-SDK\/s5ErrorP"},"doc://com.ibm.iOS-SDK/documentation/Authentication/OAuthProviderError/general(message:)":{"role":"symbol","title":"OAuthProviderError.general(message:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"general"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The authorization attempt failed for an unknown reason."}],"identifier":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/general(message:)","kind":"symbol","type":"topic","url":"\/documentation\/authentication\/oauthprovidererror\/general(message:)"},"doc://com.ibm.iOS-SDK/documentation/Authentication/OAuthProviderError":{"role":"symbol","title":"OAuthProviderError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuthProviderError"}],"abstract":[{"type":"text","text":"A type that indicates when OAuth operartion encounters an error."}],"identifier":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OAuthProviderError"}],"url":"\/documentation\/authentication\/oauthprovidererror"},"doc://com.ibm.iOS-SDK/documentation/Authentication/OAuthProviderError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/authentication\/oauthprovidererror\/equatable-implementations"},"doc://com.ibm.iOS-SDK/documentation/Authentication/OAuthProviderError/failed":{"role":"symbol","title":"OAuthProviderError.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[{"type":"text","text":"The authorization attempt failed."}],"identifier":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/failed","kind":"symbol","type":"topic","url":"\/documentation\/authentication\/oauthprovidererror\/failed"},"doc://com.ibm.iOS-SDK/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/com.ibm.iOS-SDK\/10Foundation14LocalizedErrorP"}}}